### PR TITLE
Implementing DataCoordinator and changing unlock behavior

### PR DESCRIPTION
**Pull request by zweckj**
## For dev only
@patrickhilker Do not merge before addressing #13 
- building on data coordinator to get state updates for all locks with a single API call and hopefully address #10 
- changing the unlock and open behaviors (see below for details) to address #8 and #12 
- sorting the packages with isort

## Release notes
- **CHANGED:** unlocking the lock (as well as service.unlock) now only unlocks the lock without pulling the latch
- **CHANGED:** service.open now unlocks the lock and pulls the latch if the lock is locked and pulls the latch if it is unlocked
- added a separate "Unlock & Unlatch" button to trigger the above mentioned behavior, the "Unlatch" button will only pull the latch if the door is already unlocked
- implemented re-authentication in case the token is revoked or expires
- bug fix to avoid flooding the API for people with multiple locks

### CODE REVIEW

**Comment by patrickhilker** [comment]
@zweckj there are some conflicts

**Comment by zweckj** [comment]
@patrickhilker just version conflict coming from closing #13. Resolved.

**Comment by patrickhilker** [comment]
Hey, would it be ok if I review your changes tomorrow evening? I am in a short holiday trip right now. I could create a pre release on your branch if it helps.

**Comment by zweckj** [comment]
Of course. That'd be perfect so people can test.

**Pull request merged**
